'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DBConnectionString() As String
            Get
                Return CType(Me("DBConnectionString"),String)
            End Get
            Set
                Me("DBConnectionString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BankSourceDirectory() As String
            Get
                Return CType(Me("BankSourceDirectory"),String)
            End Get
            Set
                Me("BankSourceDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BankTargetDirectory() As String
            Get
                Return CType(Me("BankTargetDirectory"),String)
            End Get
            Set
                Me("BankTargetDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DBFinance.accdb")>  _
        Public Property MDBFileName() As String
            Get
                Return CType(Me("MDBFileName"),String)
            End Get
            Set
                Me("MDBFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\ferar\Google Drive\Proyectos\HLAG\VSTO")>  _
        Public Property MDBDirectory() As String
            Get
                Return CType(Me("MDBDirectory"),String)
            End Get
            Set
                Me("MDBDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
        Public Property LookAndFeel() As String
            Get
                Return CType(Me("LookAndFeel"),String)
            End Get
            Set
                Me("LookAndFeel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerTargetDirectory1() As String
            Get
                Return CType(Me("LedgerTargetDirectory1"),String)
            End Get
            Set
                Me("LedgerTargetDirectory1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerSourceDirectory1() As String
            Get
                Return CType(Me("LedgerSourceDirectory1"),String)
            End Get
            Set
                Me("LedgerSourceDirectory1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerTargetDirectory5() As String
            Get
                Return CType(Me("LedgerTargetDirectory5"),String)
            End Get
            Set
                Me("LedgerTargetDirectory5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerSourceDirectory5() As String
            Get
                Return CType(Me("LedgerSourceDirectory5"),String)
            End Get
            Set
                Me("LedgerSourceDirectory5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerTargetDirectory6() As String
            Get
                Return CType(Me("LedgerTargetDirectory6"),String)
            End Get
            Set
                Me("LedgerTargetDirectory6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerSourceDirectory6() As String
            Get
                Return CType(Me("LedgerSourceDirectory6"),String)
            End Get
            Set
                Me("LedgerSourceDirectory6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerTargetDirectory8() As String
            Get
                Return CType(Me("LedgerTargetDirectory8"),String)
            End Get
            Set
                Me("LedgerTargetDirectory8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerSourceDirectory8() As String
            Get
                Return CType(Me("LedgerSourceDirectory8"),String)
            End Get
            Set
                Me("LedgerSourceDirectory8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerTargetDirectory14() As String
            Get
                Return CType(Me("LedgerTargetDirectory14"),String)
            End Get
            Set
                Me("LedgerTargetDirectory14") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerSourceDirectory14() As String
            Get
                Return CType(Me("LedgerSourceDirectory14"),String)
            End Get
            Set
                Me("LedgerSourceDirectory14") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MDBUser() As String
            Get
                Return CType(Me("MDBUser"),String)
            End Get
            Set
                Me("MDBUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MDBPassword() As String
            Get
                Return CType(Me("MDBPassword"),String)
            End Get
            Set
                Me("MDBPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DetraSourceDirectory() As String
            Get
                Return CType(Me("DetraSourceDirectory"),String)
            End Get
            Set
                Me("DetraSourceDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DetraTargetDirectory() As String
            Get
                Return CType(Me("DetraTargetDirectory"),String)
            End Get
            Set
                Me("DetraTargetDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RetenSourceDirectory() As String
            Get
                Return CType(Me("RetenSourceDirectory"),String)
            End Get
            Set
                Me("RetenSourceDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RetenTargetDirectory() As String
            Get
                Return CType(Me("RetenTargetDirectory"),String)
            End Get
            Set
                Me("RetenTargetDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AudioEnabled() As Boolean
            Get
                Return CType(Me("AudioEnabled"),Boolean)
            End Get
            Set
                Me("AudioEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerTargetDirectory3() As String
            Get
                Return CType(Me("LedgerTargetDirectory3"),String)
            End Get
            Set
                Me("LedgerTargetDirectory3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerSourceDirectory3() As String
            Get
                Return CType(Me("LedgerSourceDirectory3"),String)
            End Get
            Set
                Me("LedgerSourceDirectory3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ExplorerBar")>  _
        Public Property PaintStyle() As String
            Get
                Return CType(Me("PaintStyle"),String)
            End Get
            Set
                Me("PaintStyle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerTargetDirectory7() As String
            Get
                Return CType(Me("LedgerTargetDirectory7"),String)
            End Get
            Set
                Me("LedgerTargetDirectory7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerSourceDirectory7() As String
            Get
                Return CType(Me("LedgerSourceDirectory7"),String)
            End Get
            Set
                Me("LedgerSourceDirectory7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerTargetDirectory13() As String
            Get
                Return CType(Me("LedgerTargetDirectory13"),String)
            End Get
            Set
                Me("LedgerTargetDirectory13") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LedgerSourceDirectory13() As String
            Get
                Return CType(Me("LedgerSourceDirectory13"),String)
            End Get
            Set
                Me("LedgerSourceDirectory13") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.HLAG.FIN.NET.My.MySettings
            Get
                Return Global.HLAG.FIN.NET.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
