'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Z:\VSTO\PaybotHL.accdb")>  _
    Public Property DBFileName() As String
        Get
            Return CType(Me("DBFileName"),String)
        End Get
        Set
            Me("DBFileName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\\ww.hl.lan\LM2\Public\VSTO\DBHLAG.mdb")>  _
    Public Property DBFileNameBak() As String
        Get
            Return CType(Me("DBFileNameBak"),String)
        End Get
        Set
            Me("DBFileNameBak") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property DBUserName() As String
        Get
            Return CType(Me("DBUserName"),String)
        End Get
        Set
            Me("DBUserName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property DBPassword() As String
        Get
            Return CType(Me("DBPassword"),String)
        End Get
        Set
            Me("DBPassword") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\Paybot")>  _
    Public Property AttachedFilePath() As String
        Get
            Return CType(Me("AttachedFilePath"),String)
        End Get
        Set
            Me("AttachedFilePath") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ReplyAllMails() As Boolean
        Get
            Return CType(Me("ReplyAllMails"),Boolean)
        End Get
        Set
            Me("ReplyAllMails") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("4biznessolutions@gmail.com")>  _
    Public Property TOMailAddress() As String
        Get
            Return CType(Me("TOMailAddress"),String)
        End Get
        Set
            Me("TOMailAddress") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property CCMailAddress() As String
        Get
            Return CType(Me("CCMailAddress"),String)
        End Get
        Set
            Me("CCMailAddress") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property BCCMailAddress() As String
        Get
            Return CType(Me("BCCMailAddress"),String)
        End Get
        Set
            Me("BCCMailAddress") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("aremonfe@gmail.com")>  _
    Public Property SupportMailAddress() As String
        Get
            Return CType(Me("SupportMailAddress"),String)
        End Get
        Set
            Me("SupportMailAddress") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\Paybot\Log")>  _
    Public Property LogFilePath() As String
        Get
            Return CType(Me("LogFilePath"),String)
        End Get
        Set
            Me("LogFilePath") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property TRM_UserRest() As String
        Get
            Return CType(Me("TRM_UserRest"),String)
        End Get
        Set
            Me("TRM_UserRest") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property TRM_PasswordRest() As String
        Get
            Return CType(Me("TRM_PasswordRest"),String)
        End Get
        Set
            Me("TRM_PasswordRest") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("password")>  _
    Public Property TRM_GrantType() As String
        Get
            Return CType(Me("TRM_GrantType"),String)
        End Get
        Set
            Me("TRM_GrantType") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://plataformadepagosweb.tramarsa.com.pe")>  _
    Public Property TRM_UrlToken() As String
        Get
            Return CType(Me("TRM_UrlToken"),String)
        End Get
        Set
            Me("TRM_UrlToken") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("http://104.45.136.32:1717/api/deuda/")>  _
    Public Property TRM_UrlService() As String
        Get
            Return CType(Me("TRM_UrlService"),String)
        End Get
        Set
            Me("TRM_UrlService") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("http://hapagqa.paperless.com.pe/axis2/services/Online?wsdl")>  _
    Public Property PPL_UrlSoap() As String
        Get
            Return CType(Me("PPL_UrlSoap"),String)
        End Get
        Set
            Me("PPL_UrlSoap") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("adminppl")>  _
    Public Property PPL_UserSoap() As String
        Get
            Return CType(Me("PPL_UserSoap"),String)
        End Get
        Set
            Me("PPL_UserSoap") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("abc123")>  _
    Public Property PPL_PasswordSoap() As String
        Get
            Return CType(Me("PPL_PasswordSoap"),String)
        End Get
        Set
            Me("PPL_PasswordSoap") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
    Public Property PPL_TipoFolioSoap() As Integer
        Get
            Return CType(Me("PPL_TipoFolioSoap"),Integer)
        End Get
        Set
            Me("PPL_TipoFolioSoap") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property PPL_TipoRetornoSoap() As Integer
        Get
            Return CType(Me("PPL_TipoRetornoSoap"),Integer)
        End Get
        Set
            Me("PPL_TipoRetornoSoap") = value
        End Set
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("http://hapagqa.paperless.com.pe:80/axis2/services/Online.OnlineHttpSoap11Endpoint"& _ 
        "/")>  _
    Public ReadOnly Property Paybot_HapagLloydPeru_PaperlessQA_Online() As String
        Get
            Return CType(Me("Paybot_HapagLloydPeru_PaperlessQA_Online"),String)
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("20492185087")>  _
    Public Property CompanyTaxCode() As String
        Get
            Return CType(Me("CompanyTaxCode"),String)
        End Get
        Set
            Me("CompanyTaxCode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("HAPAG-LLOYD PERU S.A.C.")>  _
    Public Property CompanyName() As String
        Get
            Return CType(Me("CompanyName"),String)
        End Get
        Set
            Me("CompanyName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("CALLE DEAN VALDIVIA 148 TORRE A PISO 03")>  _
    Public Property CompanyAddress() As String
        Get
            Return CType(Me("CompanyAddress"),String)
        End Get
        Set
            Me("CompanyAddress") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("150131")>  _
    Public Property CompanyZipCode() As String
        Get
            Return CType(Me("CompanyZipCode"),String)
        End Get
        Set
            Me("CompanyZipCode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("LIMA")>  _
    Public Property CompanyDepartment() As String
        Get
            Return CType(Me("CompanyDepartment"),String)
        End Get
        Set
            Me("CompanyDepartment") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("LIMA")>  _
    Public Property CompanyProvince() As String
        Get
            Return CType(Me("CompanyProvince"),String)
        End Get
        Set
            Me("CompanyProvince") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SAN ISIDRO")>  _
    Public Property CompanyDistrict() As String
        Get
            Return CType(Me("CompanyDistrict"),String)
        End Get
        Set
            Me("CompanyDistrict") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("paybotperu@hlag.com")>  _
    Public Property SharePoint_User() As String
        Get
            Return CType(Me("SharePoint_User"),String)
        End Get
        Set
            Me("SharePoint_User") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("hapag2019")>  _
    Public Property SharePoint_Password() As String
        Get
            Return CType(Me("SharePoint_Password"),String)
        End Get
        Set
            Me("SharePoint_Password") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://hlag.sharepoint.com/sites/ITCPer")>  _
    Public Property SharePoint_Url() As String
        Get
            Return CType(Me("SharePoint_Url"),String)
        End Get
        Set
            Me("SharePoint_Url") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Paybot.HapagLloydPeru.MySettings
            Get
                Return Global.Paybot.HapagLloydPeru.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
