'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DBColdTreatment.xlsx")>  _
        Public Property DBFileName() As String
            Get
                Return CType(Me("DBFileName"),String)
            End Get
            Set
                Me("DBFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Money Twins")>  _
        Public Property LookAndFeel() As String
            Get
                Return CType(Me("LookAndFeel"),String)
            End Get
            Set
                Me("LookAndFeel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MailServerHost() As String
            Get
                Return CType(Me("MailServerHost"),String)
            End Get
            Set
                Me("MailServerHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MailServerPort() As Integer
            Get
                Return CType(Me("MailServerPort"),Integer)
            End Get
            Set
                Me("MailServerPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MailServerUser() As String
            Get
                Return CType(Me("MailServerUser"),String)
            End Get
            Set
                Me("MailServerUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MailServerPassword() As String
            Get
                Return CType(Me("MailServerPassword"),String)
            End Get
            Set
                Me("MailServerPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MailServerSsl() As Boolean
            Get
                Return CType(Me("MailServerSsl"),Boolean)
            End Get
            Set
                Me("MailServerSsl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MailTextSearch() As String
            Get
                Return CType(Me("MailTextSearch"),String)
            End Get
            Set
                Me("MailTextSearch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MailTargetPath() As String
            Get
                Return CType(Me("MailTargetPath"),String)
            End Get
            Set
                Me("MailTargetPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\ww.hl.lan\LM2\Public\VSTO")>  _
        Public Property DataSourcePath() As String
            Get
                Return CType(Me("DataSourcePath"),String)
            End Get
            Set
                Me("DataSourcePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.67")>  _
        Public Property MaxTemp() As Decimal
            Get
                Return CType(Me("MaxTemp"),Decimal)
            End Get
            Set
                Me("MaxTemp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DataTargetPath() As String
            Get
                Return CType(Me("DataTargetPath"),String)
            End Get
            Set
                Me("DataTargetPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Cesar.carranza@hlag.com;Veronica.Portella@hlag.com;Claudia.Pinillos@hlag.com")>  _
        Public Property MailTo() As String
            Get
                Return CType(Me("MailTo"),String)
            End Get
            Set
                Me("MailTo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MailSender() As String
            Get
                Return CType(Me("MailSender"),String)
            End Get
            Set
                Me("MailSender") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MailEnabled() As Boolean
            Get
                Return CType(Me("MailEnabled"),Boolean)
            End Get
            Set
                Me("MailEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property VendorSourcePath() As String
            Get
                Return CType(Me("VendorSourcePath"),String)
            End Get
            Set
                Me("VendorSourcePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dbColdTreatment.accdb")>  _
        Public Property MDBFileName() As String
            Get
                Return CType(Me("MDBFileName"),String)
            End Get
            Set
                Me("MDBFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\ww.hl.lan\LM2\Public\VSTO")>  _
        Public Property MDBDirectory() As String
            Get
                Return CType(Me("MDBDirectory"),String)
            End Get
            Set
                Me("MDBDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("90")>  _
        Public Property MaxReadingDays() As Integer
            Get
                Return CType(Me("MaxReadingDays"),Integer)
            End Get
            Set
                Me("MaxReadingDays") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("perudownload@hlag.com")>  _
        Public Property MailCC() As String
            Get
                Return CType(Me("MailCC"),String)
            End Get
            Set
                Me("MailCC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CustomDataSourceFilter() As String
            Get
                Return CType(Me("CustomDataSourceFilter"),String)
            End Get
            Set
                Me("CustomDataSourceFilter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.11")>  _
        Public Property MinTemp() As Decimal
            Get
                Return CType(Me("MinTemp"),Decimal)
            End Get
            Set
                Me("MinTemp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(";")>  _
        Public Property TextDelimiter() As String
            Get
                Return CType(Me("TextDelimiter"),String)
            End Get
            Set
                Me("TextDelimiter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AudioEnabled() As Boolean
            Get
                Return CType(Me("AudioEnabled"),Boolean)
            End Get
            Set
                Me("AudioEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("paybotperu@hlag.com")>  _
        Public Property SharePoint_User() As String
            Get
                Return CType(Me("SharePoint_User"),String)
            End Get
            Set
                Me("SharePoint_User") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("hapag2019")>  _
        Public Property SharePoint_Password() As String
            Get
                Return CType(Me("SharePoint_Password"),String)
            End Get
            Set
                Me("SharePoint_Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://hlag.sharepoint.com/sites/ITCPer")>  _
        Public Property SharePoint_Url() As String
            Get
                Return CType(Me("SharePoint_Url"),String)
            End Get
            Set
                Me("SharePoint_Url") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property DBType() As Integer
            Get
                Return CType(Me("DBType"),Integer)
            End Get
            Set
                Me("DBType") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.TCHECK.CLOUD.My.MySettings
            Get
                Return Global.TCHECK.CLOUD.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
