'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace AppService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AppService.IHapagLloydService")>  _
    Public Interface IHapagLloydService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/ExecuteSQL", ReplyAction:="http://tempuri.org/IHapagLloydService/ExecuteSQLResponse")>  _
        Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/ExecuteSQL", ReplyAction:="http://tempuri.org/IHapagLloydService/ExecuteSQLResponse")>  _
        Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/ExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IHapagLloydService/ExecuteSQLNonQueryResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function ExecuteSQLNonQuery(ByVal QueryString As String) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/ExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/IHapagLloydService/ExecuteSQLNonQueryResponse")>  _
        Function ExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/UpdateTableWithBulkCopy", ReplyAction:="http://tempuri.org/IHapagLloydService/UpdateTableWithBulkCopyResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function UpdateTableWithBulkCopy(ByVal Table As String, ByVal dtSource As System.Data.DataTable, ByVal ProcessType As String) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/UpdateTableWithBulkCopy", ReplyAction:="http://tempuri.org/IHapagLloydService/UpdateTableWithBulkCopyResponse")>  _
        Function UpdateTableWithBulkCopyAsync(ByVal Table As String, ByVal dtSource As System.Data.DataTable, ByVal ProcessType As String) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/UpdatingUsingTableAsParameter", ReplyAction:="http://tempuri.org/IHapagLloydService/UpdatingUsingTableAsParameterResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function UpdatingUsingTableAsParameter(ByVal StoreProcedure As String, ByVal Params() As Object, ByVal Values() As Object, ByVal dtSource As System.Data.DataTable) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/UpdatingUsingTableAsParameter", ReplyAction:="http://tempuri.org/IHapagLloydService/UpdatingUsingTableAsParameterResponse")>  _
        Function UpdatingUsingTableAsParameterAsync(ByVal StoreProcedure As String, ByVal Params() As Object, ByVal Values() As Object, ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/InsertContacts", ReplyAction:="http://tempuri.org/IHapagLloydService/InsertContactsResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function InsertContacts(ByVal aSource() As Object) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/InsertContacts", ReplyAction:="http://tempuri.org/IHapagLloydService/InsertContactsResponse")>  _
        Function InsertContactsAsync(ByVal aSource() As Object) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/InsertBlackList", ReplyAction:="http://tempuri.org/IHapagLloydService/InsertBlackListResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function InsertBlackList(ByVal aSource() As Object) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/InsertBlackList", ReplyAction:="http://tempuri.org/IHapagLloydService/InsertBlackListResponse")>  _
        Function InsertBlackListAsync(ByVal aSource() As Object) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/InsertColdTreatment", ReplyAction:="http://tempuri.org/IHapagLloydService/InsertColdTreatmentResponse")>  _
        Function InsertColdTreatment(ByVal dtSource As System.Data.DataTable) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/InsertColdTreatment", ReplyAction:="http://tempuri.org/IHapagLloydService/InsertColdTreatmentResponse")>  _
        Function InsertColdTreatmentAsync(ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/UpdateColdTreatment", ReplyAction:="http://tempuri.org/IHapagLloydService/UpdateColdTreatmentResponse")>  _
        Function UpdateColdTreatment(ByVal dtSource As System.Data.DataTable) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/UpdateColdTreatment", ReplyAction:="http://tempuri.org/IHapagLloydService/UpdateColdTreatmentResponse")>  _
        Function UpdateColdTreatmentAsync(ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/DeleteColdTreatment", ReplyAction:="http://tempuri.org/IHapagLloydService/DeleteColdTreatmentResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function DeleteColdTreatment(ByVal aSource() As Object) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/DeleteColdTreatment", ReplyAction:="http://tempuri.org/IHapagLloydService/DeleteColdTreatmentResponse")>  _
        Function DeleteColdTreatmentAsync(ByVal aSource() As Object) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/InsertColdTreatmentEvents", ReplyAction:="http://tempuri.org/IHapagLloydService/InsertColdTreatmentEventsResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function InsertColdTreatmentEvents(ByVal aSource() As Object) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/InsertColdTreatmentEvents", ReplyAction:="http://tempuri.org/IHapagLloydService/InsertColdTreatmentEventsResponse")>  _
        Function InsertColdTreatmentEventsAsync(ByVal aSource() As Object) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/DeleteColdTreatmentEvents", ReplyAction:="http://tempuri.org/IHapagLloydService/DeleteColdTreatmentEventsResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function DeleteColdTreatmentEvents(ByVal aSource() As Object) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/DeleteColdTreatmentEvents", ReplyAction:="http://tempuri.org/IHapagLloydService/DeleteColdTreatmentEventsResponse")>  _
        Function DeleteColdTreatmentEventsAsync(ByVal aSource() As Object) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/InsertColdTreatmentReadings", ReplyAction:="http://tempuri.org/IHapagLloydService/InsertColdTreatmentReadingsResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function InsertColdTreatmentReadings(ByVal aSource() As Object) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/InsertColdTreatmentReadings", ReplyAction:="http://tempuri.org/IHapagLloydService/InsertColdTreatmentReadingsResponse")>  _
        Function InsertColdTreatmentReadingsAsync(ByVal aSource() As Object) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/DeleteColdTreatmentReadings", ReplyAction:="http://tempuri.org/IHapagLloydService/DeleteColdTreatmentReadingsResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function DeleteColdTreatmentReadings(ByVal aSource() As Object) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/DeleteColdTreatmentReadings", ReplyAction:="http://tempuri.org/IHapagLloydService/DeleteColdTreatmentReadingsResponse")>  _
        Function DeleteColdTreatmentReadingsAsync(ByVal aSource() As Object) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/InsertScheduleVoyage", ReplyAction:="http://tempuri.org/IHapagLloydService/InsertScheduleVoyageResponse")>  _
        Function InsertScheduleVoyage(ByVal dtSource As System.Data.DataTable) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/InsertScheduleVoyage", ReplyAction:="http://tempuri.org/IHapagLloydService/InsertScheduleVoyageResponse")>  _
        Function InsertScheduleVoyageAsync(ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/InsertReeferDataMaster", ReplyAction:="http://tempuri.org/IHapagLloydService/InsertReeferDataMasterResponse")>  _
        Function InsertReeferDataMaster(ByVal dtSource As System.Data.DataTable) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHapagLloydService/InsertReeferDataMaster", ReplyAction:="http://tempuri.org/IHapagLloydService/InsertReeferDataMasterResponse")>  _
        Function InsertReeferDataMasterAsync(ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IHapagLloydServiceChannel
        Inherits AppService.IHapagLloydService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class HapagLloydServiceClient
        Inherits System.ServiceModel.ClientBase(Of AppService.IHapagLloydService)
        Implements AppService.IHapagLloydService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet Implements AppService.IHapagLloydService.ExecuteSQL
            Return MyBase.Channel.ExecuteSQL(QueryString)
        End Function
        
        Public Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements AppService.IHapagLloydService.ExecuteSQLAsync
            Return MyBase.Channel.ExecuteSQLAsync(QueryString)
        End Function
        
        Public Function ExecuteSQLNonQuery(ByVal QueryString As String) As Object() Implements AppService.IHapagLloydService.ExecuteSQLNonQuery
            Return MyBase.Channel.ExecuteSQLNonQuery(QueryString)
        End Function
        
        Public Function ExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Object()) Implements AppService.IHapagLloydService.ExecuteSQLNonQueryAsync
            Return MyBase.Channel.ExecuteSQLNonQueryAsync(QueryString)
        End Function
        
        Public Function UpdateTableWithBulkCopy(ByVal Table As String, ByVal dtSource As System.Data.DataTable, ByVal ProcessType As String) As Object() Implements AppService.IHapagLloydService.UpdateTableWithBulkCopy
            Return MyBase.Channel.UpdateTableWithBulkCopy(Table, dtSource, ProcessType)
        End Function
        
        Public Function UpdateTableWithBulkCopyAsync(ByVal Table As String, ByVal dtSource As System.Data.DataTable, ByVal ProcessType As String) As System.Threading.Tasks.Task(Of Object()) Implements AppService.IHapagLloydService.UpdateTableWithBulkCopyAsync
            Return MyBase.Channel.UpdateTableWithBulkCopyAsync(Table, dtSource, ProcessType)
        End Function
        
        Public Function UpdatingUsingTableAsParameter(ByVal StoreProcedure As String, ByVal Params() As Object, ByVal Values() As Object, ByVal dtSource As System.Data.DataTable) As Object() Implements AppService.IHapagLloydService.UpdatingUsingTableAsParameter
            Return MyBase.Channel.UpdatingUsingTableAsParameter(StoreProcedure, Params, Values, dtSource)
        End Function
        
        Public Function UpdatingUsingTableAsParameterAsync(ByVal StoreProcedure As String, ByVal Params() As Object, ByVal Values() As Object, ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Object()) Implements AppService.IHapagLloydService.UpdatingUsingTableAsParameterAsync
            Return MyBase.Channel.UpdatingUsingTableAsParameterAsync(StoreProcedure, Params, Values, dtSource)
        End Function
        
        Public Function InsertContacts(ByVal aSource() As Object) As Boolean Implements AppService.IHapagLloydService.InsertContacts
            Return MyBase.Channel.InsertContacts(aSource)
        End Function
        
        Public Function InsertContactsAsync(ByVal aSource() As Object) As System.Threading.Tasks.Task(Of Boolean) Implements AppService.IHapagLloydService.InsertContactsAsync
            Return MyBase.Channel.InsertContactsAsync(aSource)
        End Function
        
        Public Function InsertBlackList(ByVal aSource() As Object) As Boolean Implements AppService.IHapagLloydService.InsertBlackList
            Return MyBase.Channel.InsertBlackList(aSource)
        End Function
        
        Public Function InsertBlackListAsync(ByVal aSource() As Object) As System.Threading.Tasks.Task(Of Boolean) Implements AppService.IHapagLloydService.InsertBlackListAsync
            Return MyBase.Channel.InsertBlackListAsync(aSource)
        End Function
        
        Public Function InsertColdTreatment(ByVal dtSource As System.Data.DataTable) As Boolean Implements AppService.IHapagLloydService.InsertColdTreatment
            Return MyBase.Channel.InsertColdTreatment(dtSource)
        End Function
        
        Public Function InsertColdTreatmentAsync(ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Boolean) Implements AppService.IHapagLloydService.InsertColdTreatmentAsync
            Return MyBase.Channel.InsertColdTreatmentAsync(dtSource)
        End Function
        
        Public Function UpdateColdTreatment(ByVal dtSource As System.Data.DataTable) As Boolean Implements AppService.IHapagLloydService.UpdateColdTreatment
            Return MyBase.Channel.UpdateColdTreatment(dtSource)
        End Function
        
        Public Function UpdateColdTreatmentAsync(ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Boolean) Implements AppService.IHapagLloydService.UpdateColdTreatmentAsync
            Return MyBase.Channel.UpdateColdTreatmentAsync(dtSource)
        End Function
        
        Public Function DeleteColdTreatment(ByVal aSource() As Object) As Boolean Implements AppService.IHapagLloydService.DeleteColdTreatment
            Return MyBase.Channel.DeleteColdTreatment(aSource)
        End Function
        
        Public Function DeleteColdTreatmentAsync(ByVal aSource() As Object) As System.Threading.Tasks.Task(Of Boolean) Implements AppService.IHapagLloydService.DeleteColdTreatmentAsync
            Return MyBase.Channel.DeleteColdTreatmentAsync(aSource)
        End Function
        
        Public Function InsertColdTreatmentEvents(ByVal aSource() As Object) As Boolean Implements AppService.IHapagLloydService.InsertColdTreatmentEvents
            Return MyBase.Channel.InsertColdTreatmentEvents(aSource)
        End Function
        
        Public Function InsertColdTreatmentEventsAsync(ByVal aSource() As Object) As System.Threading.Tasks.Task(Of Boolean) Implements AppService.IHapagLloydService.InsertColdTreatmentEventsAsync
            Return MyBase.Channel.InsertColdTreatmentEventsAsync(aSource)
        End Function
        
        Public Function DeleteColdTreatmentEvents(ByVal aSource() As Object) As Boolean Implements AppService.IHapagLloydService.DeleteColdTreatmentEvents
            Return MyBase.Channel.DeleteColdTreatmentEvents(aSource)
        End Function
        
        Public Function DeleteColdTreatmentEventsAsync(ByVal aSource() As Object) As System.Threading.Tasks.Task(Of Boolean) Implements AppService.IHapagLloydService.DeleteColdTreatmentEventsAsync
            Return MyBase.Channel.DeleteColdTreatmentEventsAsync(aSource)
        End Function
        
        Public Function InsertColdTreatmentReadings(ByVal aSource() As Object) As Boolean Implements AppService.IHapagLloydService.InsertColdTreatmentReadings
            Return MyBase.Channel.InsertColdTreatmentReadings(aSource)
        End Function
        
        Public Function InsertColdTreatmentReadingsAsync(ByVal aSource() As Object) As System.Threading.Tasks.Task(Of Boolean) Implements AppService.IHapagLloydService.InsertColdTreatmentReadingsAsync
            Return MyBase.Channel.InsertColdTreatmentReadingsAsync(aSource)
        End Function
        
        Public Function DeleteColdTreatmentReadings(ByVal aSource() As Object) As Boolean Implements AppService.IHapagLloydService.DeleteColdTreatmentReadings
            Return MyBase.Channel.DeleteColdTreatmentReadings(aSource)
        End Function
        
        Public Function DeleteColdTreatmentReadingsAsync(ByVal aSource() As Object) As System.Threading.Tasks.Task(Of Boolean) Implements AppService.IHapagLloydService.DeleteColdTreatmentReadingsAsync
            Return MyBase.Channel.DeleteColdTreatmentReadingsAsync(aSource)
        End Function
        
        Public Function InsertScheduleVoyage(ByVal dtSource As System.Data.DataTable) As Boolean Implements AppService.IHapagLloydService.InsertScheduleVoyage
            Return MyBase.Channel.InsertScheduleVoyage(dtSource)
        End Function
        
        Public Function InsertScheduleVoyageAsync(ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Boolean) Implements AppService.IHapagLloydService.InsertScheduleVoyageAsync
            Return MyBase.Channel.InsertScheduleVoyageAsync(dtSource)
        End Function
        
        Public Function InsertReeferDataMaster(ByVal dtSource As System.Data.DataTable) As Boolean Implements AppService.IHapagLloydService.InsertReeferDataMaster
            Return MyBase.Channel.InsertReeferDataMaster(dtSource)
        End Function
        
        Public Function InsertReeferDataMasterAsync(ByVal dtSource As System.Data.DataTable) As System.Threading.Tasks.Task(Of Boolean) Implements AppService.IHapagLloydService.InsertReeferDataMasterAsync
            Return MyBase.Channel.InsertReeferDataMasterAsync(dtSource)
        End Function
    End Class
End Namespace
