'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace PaperlessQA
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="OnlineSoap11Binding", [Namespace]:="http://ws.online.asp.core.paperless.cl")>  _
    Partial Public Class Online
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private InformeResBoletasDiarioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AddDocInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private OnlineARCOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GenInformeReversionesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private OnlineEventosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CargaInformeBajasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaInformeReversionesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private OnlineRecoveryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private OnlineRecoveryRecOperationCompleted As System.Threading.SendOrPostCallback
        
        Private OnlineRecoveryRecListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private listarAdjuntosRecibidosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private OnlineConsultaEstadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private OnlineGenerationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Paybot.HapagLloydPeru.MySettings.Default.Paybot_HapagLloydPeru_PaperlessQA_Online
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event InformeResBoletasDiarioCompleted As InformeResBoletasDiarioCompletedEventHandler
        
        '''<remarks/>
        Public Event AddDocInfoCompleted As AddDocInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event OnlineARCCompleted As OnlineARCCompletedEventHandler
        
        '''<remarks/>
        Public Event GenInformeReversionesCompleted As GenInformeReversionesCompletedEventHandler
        
        '''<remarks/>
        Public Event OnlineEventosCompleted As OnlineEventosCompletedEventHandler
        
        '''<remarks/>
        Public Event CargaInformeBajasCompleted As CargaInformeBajasCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaInformeReversionesCompleted As ConsultaInformeReversionesCompletedEventHandler
        
        '''<remarks/>
        Public Event OnlineRecoveryCompleted As OnlineRecoveryCompletedEventHandler
        
        '''<remarks/>
        Public Event OnlineRecoveryRecCompleted As OnlineRecoveryRecCompletedEventHandler
        
        '''<remarks/>
        Public Event OnlineRecoveryRecListCompleted As OnlineRecoveryRecListCompletedEventHandler
        
        '''<remarks/>
        Public Event listarAdjuntosRecibidosCompleted As listarAdjuntosRecibidosCompletedEventHandler
        
        '''<remarks/>
        Public Event OnlineConsultaEstadoCompleted As OnlineConsultaEstadoCompletedEventHandler
        
        '''<remarks/>
        Public Event OnlineGenerationCompleted As OnlineGenerationCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultCompleted As ConsultCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:InformeResBoletasDiario", RequestNamespace:="http://ws.online.asp.core.paperless.cl", ResponseNamespace:="http://ws.online.asp.core.paperless.cl", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InformeResBoletasDiario(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ruc As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal login As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clave As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal fechaInforme As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("InformeResBoletasDiario", New Object() {ruc, login, clave, fechaInforme})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InformeResBoletasDiarioAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal fechaInforme As String)
            Me.InformeResBoletasDiarioAsync(ruc, login, clave, fechaInforme, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InformeResBoletasDiarioAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal fechaInforme As String, ByVal userState As Object)
            If (Me.InformeResBoletasDiarioOperationCompleted Is Nothing) Then
                Me.InformeResBoletasDiarioOperationCompleted = AddressOf Me.OnInformeResBoletasDiarioOperationCompleted
            End If
            Me.InvokeAsync("InformeResBoletasDiario", New Object() {ruc, login, clave, fechaInforme}, Me.InformeResBoletasDiarioOperationCompleted, userState)
        End Sub
        
        Private Sub OnInformeResBoletasDiarioOperationCompleted(ByVal arg As Object)
            If (Not (Me.InformeResBoletasDiarioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InformeResBoletasDiarioCompleted(Me, New InformeResBoletasDiarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:AddDocInfo", RequestNamespace:="http://ws.online.asp.core.paperless.cl", ResponseNamespace:="http://ws.online.asp.core.paperless.cl", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddDocInfo(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ruc As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal login As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clave As String, ByVal tipoDoc As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal tipoDocSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal folio As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal infoAdicional As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("AddDocInfo", New Object() {ruc, login, clave, tipoDoc, tipoDocSpecified, folio, infoAdicional})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AddDocInfoAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal tipoDoc As Integer, ByVal tipoDocSpecified As Boolean, ByVal folio As String, ByVal infoAdicional As String)
            Me.AddDocInfoAsync(ruc, login, clave, tipoDoc, tipoDocSpecified, folio, infoAdicional, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddDocInfoAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal tipoDoc As Integer, ByVal tipoDocSpecified As Boolean, ByVal folio As String, ByVal infoAdicional As String, ByVal userState As Object)
            If (Me.AddDocInfoOperationCompleted Is Nothing) Then
                Me.AddDocInfoOperationCompleted = AddressOf Me.OnAddDocInfoOperationCompleted
            End If
            Me.InvokeAsync("AddDocInfo", New Object() {ruc, login, clave, tipoDoc, tipoDocSpecified, folio, infoAdicional}, Me.AddDocInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddDocInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddDocInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddDocInfoCompleted(Me, New AddDocInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:OnlineARC", RequestNamespace:="http://ws.online.asp.core.paperless.cl", ResponseNamespace:="http://ws.online.asp.core.paperless.cl", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function OnlineARC(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ruc As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal login As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clave As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal rucEmisor As String, ByVal tipoDoc As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal tipoDocSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal folio As String, ByVal estado As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal estadoSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal version As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("OnlineARC", New Object() {ruc, login, clave, rucEmisor, tipoDoc, tipoDocSpecified, folio, estado, estadoSpecified, version})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub OnlineARCAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal rucEmisor As String, ByVal tipoDoc As Integer, ByVal tipoDocSpecified As Boolean, ByVal folio As String, ByVal estado As Integer, ByVal estadoSpecified As Boolean, ByVal version As String)
            Me.OnlineARCAsync(ruc, login, clave, rucEmisor, tipoDoc, tipoDocSpecified, folio, estado, estadoSpecified, version, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub OnlineARCAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal rucEmisor As String, ByVal tipoDoc As Integer, ByVal tipoDocSpecified As Boolean, ByVal folio As String, ByVal estado As Integer, ByVal estadoSpecified As Boolean, ByVal version As String, ByVal userState As Object)
            If (Me.OnlineARCOperationCompleted Is Nothing) Then
                Me.OnlineARCOperationCompleted = AddressOf Me.OnOnlineARCOperationCompleted
            End If
            Me.InvokeAsync("OnlineARC", New Object() {ruc, login, clave, rucEmisor, tipoDoc, tipoDocSpecified, folio, estado, estadoSpecified, version}, Me.OnlineARCOperationCompleted, userState)
        End Sub
        
        Private Sub OnOnlineARCOperationCompleted(ByVal arg As Object)
            If (Not (Me.OnlineARCCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent OnlineARCCompleted(Me, New OnlineARCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GenInformeReversiones", RequestNamespace:="http://ws.online.asp.core.paperless.cl", ResponseNamespace:="http://ws.online.asp.core.paperless.cl", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GenInformeReversiones(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ruc As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal login As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clave As String, ByVal tpoGen As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal tpoGenSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal tramaTxt As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal periodo As String, ByVal envioSUNAT As Boolean, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal envioSUNATSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("GenInformeReversiones", New Object() {ruc, login, clave, tpoGen, tpoGenSpecified, tramaTxt, periodo, envioSUNAT, envioSUNATSpecified})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GenInformeReversionesAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal tpoGen As Integer, ByVal tpoGenSpecified As Boolean, ByVal tramaTxt As String, ByVal periodo As String, ByVal envioSUNAT As Boolean, ByVal envioSUNATSpecified As Boolean)
            Me.GenInformeReversionesAsync(ruc, login, clave, tpoGen, tpoGenSpecified, tramaTxt, periodo, envioSUNAT, envioSUNATSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GenInformeReversionesAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal tpoGen As Integer, ByVal tpoGenSpecified As Boolean, ByVal tramaTxt As String, ByVal periodo As String, ByVal envioSUNAT As Boolean, ByVal envioSUNATSpecified As Boolean, ByVal userState As Object)
            If (Me.GenInformeReversionesOperationCompleted Is Nothing) Then
                Me.GenInformeReversionesOperationCompleted = AddressOf Me.OnGenInformeReversionesOperationCompleted
            End If
            Me.InvokeAsync("GenInformeReversiones", New Object() {ruc, login, clave, tpoGen, tpoGenSpecified, tramaTxt, periodo, envioSUNAT, envioSUNATSpecified}, Me.GenInformeReversionesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGenInformeReversionesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GenInformeReversionesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GenInformeReversionesCompleted(Me, New GenInformeReversionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:OnlineEventos", RequestNamespace:="http://ws.online.asp.core.paperless.cl", ResponseNamespace:="http://ws.online.asp.core.paperless.cl", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function OnlineEventos(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ruc As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal login As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clave As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal docTxt As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("OnlineEventos", New Object() {ruc, login, clave, docTxt})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub OnlineEventosAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal docTxt As String)
            Me.OnlineEventosAsync(ruc, login, clave, docTxt, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub OnlineEventosAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal docTxt As String, ByVal userState As Object)
            If (Me.OnlineEventosOperationCompleted Is Nothing) Then
                Me.OnlineEventosOperationCompleted = AddressOf Me.OnOnlineEventosOperationCompleted
            End If
            Me.InvokeAsync("OnlineEventos", New Object() {ruc, login, clave, docTxt}, Me.OnlineEventosOperationCompleted, userState)
        End Sub
        
        Private Sub OnOnlineEventosOperationCompleted(ByVal arg As Object)
            If (Not (Me.OnlineEventosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent OnlineEventosCompleted(Me, New OnlineEventosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:CargaInformeBajas", RequestNamespace:="http://ws.online.asp.core.paperless.cl", ResponseNamespace:="http://ws.online.asp.core.paperless.cl", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CargaInformeBajas(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ruc As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal login As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clave As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal docTxt As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal periodo As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("CargaInformeBajas", New Object() {ruc, login, clave, docTxt, periodo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CargaInformeBajasAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal docTxt As String, ByVal periodo As String)
            Me.CargaInformeBajasAsync(ruc, login, clave, docTxt, periodo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CargaInformeBajasAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal docTxt As String, ByVal periodo As String, ByVal userState As Object)
            If (Me.CargaInformeBajasOperationCompleted Is Nothing) Then
                Me.CargaInformeBajasOperationCompleted = AddressOf Me.OnCargaInformeBajasOperationCompleted
            End If
            Me.InvokeAsync("CargaInformeBajas", New Object() {ruc, login, clave, docTxt, periodo}, Me.CargaInformeBajasOperationCompleted, userState)
        End Sub
        
        Private Sub OnCargaInformeBajasOperationCompleted(ByVal arg As Object)
            If (Not (Me.CargaInformeBajasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CargaInformeBajasCompleted(Me, New CargaInformeBajasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ConsultaInformeReversiones", RequestNamespace:="http://ws.online.asp.core.paperless.cl", ResponseNamespace:="http://ws.online.asp.core.paperless.cl", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaInformeReversiones(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ruc As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal login As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clave As String, ByVal idRegistro As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal idRegistroSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal numTicketSunat As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("ConsultaInformeReversiones", New Object() {ruc, login, clave, idRegistro, idRegistroSpecified, numTicketSunat})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaInformeReversionesAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal idRegistro As Integer, ByVal idRegistroSpecified As Boolean, ByVal numTicketSunat As String)
            Me.ConsultaInformeReversionesAsync(ruc, login, clave, idRegistro, idRegistroSpecified, numTicketSunat, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaInformeReversionesAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal idRegistro As Integer, ByVal idRegistroSpecified As Boolean, ByVal numTicketSunat As String, ByVal userState As Object)
            If (Me.ConsultaInformeReversionesOperationCompleted Is Nothing) Then
                Me.ConsultaInformeReversionesOperationCompleted = AddressOf Me.OnConsultaInformeReversionesOperationCompleted
            End If
            Me.InvokeAsync("ConsultaInformeReversiones", New Object() {ruc, login, clave, idRegistro, idRegistroSpecified, numTicketSunat}, Me.ConsultaInformeReversionesOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaInformeReversionesOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaInformeReversionesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaInformeReversionesCompleted(Me, New ConsultaInformeReversionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:OnlineRecovery", RequestNamespace:="http://ws.online.asp.core.paperless.cl", ResponseNamespace:="http://ws.online.asp.core.paperless.cl", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function OnlineRecovery(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ruc As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal login As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clave As String, ByVal tipoDoc As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal tipoDocSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal folio As String, ByVal tipoRetorno As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal tipoRetornoSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("OnlineRecovery", New Object() {ruc, login, clave, tipoDoc, tipoDocSpecified, folio, tipoRetorno, tipoRetornoSpecified})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub OnlineRecoveryAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal tipoDoc As Integer, ByVal tipoDocSpecified As Boolean, ByVal folio As String, ByVal tipoRetorno As Integer, ByVal tipoRetornoSpecified As Boolean)
            Me.OnlineRecoveryAsync(ruc, login, clave, tipoDoc, tipoDocSpecified, folio, tipoRetorno, tipoRetornoSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub OnlineRecoveryAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal tipoDoc As Integer, ByVal tipoDocSpecified As Boolean, ByVal folio As String, ByVal tipoRetorno As Integer, ByVal tipoRetornoSpecified As Boolean, ByVal userState As Object)
            If (Me.OnlineRecoveryOperationCompleted Is Nothing) Then
                Me.OnlineRecoveryOperationCompleted = AddressOf Me.OnOnlineRecoveryOperationCompleted
            End If
            Me.InvokeAsync("OnlineRecovery", New Object() {ruc, login, clave, tipoDoc, tipoDocSpecified, folio, tipoRetorno, tipoRetornoSpecified}, Me.OnlineRecoveryOperationCompleted, userState)
        End Sub
        
        Private Sub OnOnlineRecoveryOperationCompleted(ByVal arg As Object)
            If (Not (Me.OnlineRecoveryCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent OnlineRecoveryCompleted(Me, New OnlineRecoveryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:OnlineRecoveryRec", RequestNamespace:="http://ws.online.asp.core.paperless.cl", ResponseNamespace:="http://ws.online.asp.core.paperless.cl", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function OnlineRecoveryRec(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ruc As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal login As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clave As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal rucEmisor As String, ByVal tipoDoc As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal tipoDocSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal folio As String, ByVal tipoRetorno As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal tipoRetornoSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("OnlineRecoveryRec", New Object() {ruc, login, clave, rucEmisor, tipoDoc, tipoDocSpecified, folio, tipoRetorno, tipoRetornoSpecified})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub OnlineRecoveryRecAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal rucEmisor As String, ByVal tipoDoc As Integer, ByVal tipoDocSpecified As Boolean, ByVal folio As String, ByVal tipoRetorno As Integer, ByVal tipoRetornoSpecified As Boolean)
            Me.OnlineRecoveryRecAsync(ruc, login, clave, rucEmisor, tipoDoc, tipoDocSpecified, folio, tipoRetorno, tipoRetornoSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub OnlineRecoveryRecAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal rucEmisor As String, ByVal tipoDoc As Integer, ByVal tipoDocSpecified As Boolean, ByVal folio As String, ByVal tipoRetorno As Integer, ByVal tipoRetornoSpecified As Boolean, ByVal userState As Object)
            If (Me.OnlineRecoveryRecOperationCompleted Is Nothing) Then
                Me.OnlineRecoveryRecOperationCompleted = AddressOf Me.OnOnlineRecoveryRecOperationCompleted
            End If
            Me.InvokeAsync("OnlineRecoveryRec", New Object() {ruc, login, clave, rucEmisor, tipoDoc, tipoDocSpecified, folio, tipoRetorno, tipoRetornoSpecified}, Me.OnlineRecoveryRecOperationCompleted, userState)
        End Sub
        
        Private Sub OnOnlineRecoveryRecOperationCompleted(ByVal arg As Object)
            If (Not (Me.OnlineRecoveryRecCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent OnlineRecoveryRecCompleted(Me, New OnlineRecoveryRecCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:OnlineRecoveryRecList", RequestNamespace:="http://ws.online.asp.core.paperless.cl", ResponseNamespace:="http://ws.online.asp.core.paperless.cl", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function OnlineRecoveryRecList(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ruc As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal login As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clave As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal fecha As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("OnlineRecoveryRecList", New Object() {ruc, login, clave, fecha})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub OnlineRecoveryRecListAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal fecha As String)
            Me.OnlineRecoveryRecListAsync(ruc, login, clave, fecha, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub OnlineRecoveryRecListAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal fecha As String, ByVal userState As Object)
            If (Me.OnlineRecoveryRecListOperationCompleted Is Nothing) Then
                Me.OnlineRecoveryRecListOperationCompleted = AddressOf Me.OnOnlineRecoveryRecListOperationCompleted
            End If
            Me.InvokeAsync("OnlineRecoveryRecList", New Object() {ruc, login, clave, fecha}, Me.OnlineRecoveryRecListOperationCompleted, userState)
        End Sub
        
        Private Sub OnOnlineRecoveryRecListOperationCompleted(ByVal arg As Object)
            If (Not (Me.OnlineRecoveryRecListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent OnlineRecoveryRecListCompleted(Me, New OnlineRecoveryRecListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:listarAdjuntosRecibidos", RequestNamespace:="http://ws.online.asp.core.paperless.cl", ResponseNamespace:="http://ws.online.asp.core.paperless.cl", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function listarAdjuntosRecibidos(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ruc As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal login As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clave As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal rucEmisor As String, ByVal tipoDocumento As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal tipoDocumentoSpecified As Boolean, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal folio As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("listarAdjuntosRecibidos", New Object() {ruc, login, clave, rucEmisor, tipoDocumento, tipoDocumentoSpecified, folio})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub listarAdjuntosRecibidosAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal rucEmisor As String, ByVal tipoDocumento As Integer, ByVal tipoDocumentoSpecified As Boolean, ByVal folio As String)
            Me.listarAdjuntosRecibidosAsync(ruc, login, clave, rucEmisor, tipoDocumento, tipoDocumentoSpecified, folio, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub listarAdjuntosRecibidosAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal rucEmisor As String, ByVal tipoDocumento As Integer, ByVal tipoDocumentoSpecified As Boolean, ByVal folio As String, ByVal userState As Object)
            If (Me.listarAdjuntosRecibidosOperationCompleted Is Nothing) Then
                Me.listarAdjuntosRecibidosOperationCompleted = AddressOf Me.OnlistarAdjuntosRecibidosOperationCompleted
            End If
            Me.InvokeAsync("listarAdjuntosRecibidos", New Object() {ruc, login, clave, rucEmisor, tipoDocumento, tipoDocumentoSpecified, folio}, Me.listarAdjuntosRecibidosOperationCompleted, userState)
        End Sub
        
        Private Sub OnlistarAdjuntosRecibidosOperationCompleted(ByVal arg As Object)
            If (Not (Me.listarAdjuntosRecibidosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent listarAdjuntosRecibidosCompleted(Me, New listarAdjuntosRecibidosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:OnlineConsultaEstado", RequestNamespace:="http://ws.online.asp.core.paperless.cl", ResponseNamespace:="http://ws.online.asp.core.paperless.cl", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function OnlineConsultaEstado(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ruc As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal login As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clave As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal rucReceptor As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal fechaInicio As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal fechaFin As String, ByVal estado As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal estadoSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("OnlineConsultaEstado", New Object() {ruc, login, clave, rucReceptor, fechaInicio, fechaFin, estado, estadoSpecified})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub OnlineConsultaEstadoAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal rucReceptor As String, ByVal fechaInicio As String, ByVal fechaFin As String, ByVal estado As Integer, ByVal estadoSpecified As Boolean)
            Me.OnlineConsultaEstadoAsync(ruc, login, clave, rucReceptor, fechaInicio, fechaFin, estado, estadoSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub OnlineConsultaEstadoAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal rucReceptor As String, ByVal fechaInicio As String, ByVal fechaFin As String, ByVal estado As Integer, ByVal estadoSpecified As Boolean, ByVal userState As Object)
            If (Me.OnlineConsultaEstadoOperationCompleted Is Nothing) Then
                Me.OnlineConsultaEstadoOperationCompleted = AddressOf Me.OnOnlineConsultaEstadoOperationCompleted
            End If
            Me.InvokeAsync("OnlineConsultaEstado", New Object() {ruc, login, clave, rucReceptor, fechaInicio, fechaFin, estado, estadoSpecified}, Me.OnlineConsultaEstadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnOnlineConsultaEstadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.OnlineConsultaEstadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent OnlineConsultaEstadoCompleted(Me, New OnlineConsultaEstadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:OnlineGeneration", RequestNamespace:="http://ws.online.asp.core.paperless.cl", ResponseNamespace:="http://ws.online.asp.core.paperless.cl", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function OnlineGeneration(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ruc As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal login As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clave As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal docTxt As String, ByVal tipoFoliacion As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal tipoFoliacionSpecified As Boolean, ByVal tipoRetorno As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal tipoRetornoSpecified As Boolean) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("OnlineGeneration", New Object() {ruc, login, clave, docTxt, tipoFoliacion, tipoFoliacionSpecified, tipoRetorno, tipoRetornoSpecified})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub OnlineGenerationAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal docTxt As String, ByVal tipoFoliacion As Integer, ByVal tipoFoliacionSpecified As Boolean, ByVal tipoRetorno As Integer, ByVal tipoRetornoSpecified As Boolean)
            Me.OnlineGenerationAsync(ruc, login, clave, docTxt, tipoFoliacion, tipoFoliacionSpecified, tipoRetorno, tipoRetornoSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub OnlineGenerationAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal docTxt As String, ByVal tipoFoliacion As Integer, ByVal tipoFoliacionSpecified As Boolean, ByVal tipoRetorno As Integer, ByVal tipoRetornoSpecified As Boolean, ByVal userState As Object)
            If (Me.OnlineGenerationOperationCompleted Is Nothing) Then
                Me.OnlineGenerationOperationCompleted = AddressOf Me.OnOnlineGenerationOperationCompleted
            End If
            Me.InvokeAsync("OnlineGeneration", New Object() {ruc, login, clave, docTxt, tipoFoliacion, tipoFoliacionSpecified, tipoRetorno, tipoRetornoSpecified}, Me.OnlineGenerationOperationCompleted, userState)
        End Sub
        
        Private Sub OnOnlineGenerationOperationCompleted(ByVal arg As Object)
            If (Not (Me.OnlineGenerationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent OnlineGenerationCompleted(Me, New OnlineGenerationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Consult", RequestNamespace:="http://ws.online.asp.core.paperless.cl", ResponseNamespace:="http://ws.online.asp.core.paperless.cl", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Consult(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal ruc As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal login As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal clave As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal params As String) As <System.Xml.Serialization.XmlElementAttribute("return", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("Consult", New Object() {ruc, login, clave, params})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal params As String)
            Me.ConsultAsync(ruc, login, clave, params, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultAsync(ByVal ruc As String, ByVal login As String, ByVal clave As String, ByVal params As String, ByVal userState As Object)
            If (Me.ConsultOperationCompleted Is Nothing) Then
                Me.ConsultOperationCompleted = AddressOf Me.OnConsultOperationCompleted
            End If
            Me.InvokeAsync("Consult", New Object() {ruc, login, clave, params}, Me.ConsultOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultCompleted(Me, New ConsultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub InformeResBoletasDiarioCompletedEventHandler(ByVal sender As Object, ByVal e As InformeResBoletasDiarioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InformeResBoletasDiarioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub AddDocInfoCompletedEventHandler(ByVal sender As Object, ByVal e As AddDocInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AddDocInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub OnlineARCCompletedEventHandler(ByVal sender As Object, ByVal e As OnlineARCCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class OnlineARCCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GenInformeReversionesCompletedEventHandler(ByVal sender As Object, ByVal e As GenInformeReversionesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GenInformeReversionesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub OnlineEventosCompletedEventHandler(ByVal sender As Object, ByVal e As OnlineEventosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class OnlineEventosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub CargaInformeBajasCompletedEventHandler(ByVal sender As Object, ByVal e As CargaInformeBajasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CargaInformeBajasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ConsultaInformeReversionesCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaInformeReversionesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaInformeReversionesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub OnlineRecoveryCompletedEventHandler(ByVal sender As Object, ByVal e As OnlineRecoveryCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class OnlineRecoveryCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub OnlineRecoveryRecCompletedEventHandler(ByVal sender As Object, ByVal e As OnlineRecoveryRecCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class OnlineRecoveryRecCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub OnlineRecoveryRecListCompletedEventHandler(ByVal sender As Object, ByVal e As OnlineRecoveryRecListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class OnlineRecoveryRecListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub listarAdjuntosRecibidosCompletedEventHandler(ByVal sender As Object, ByVal e As listarAdjuntosRecibidosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class listarAdjuntosRecibidosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub OnlineConsultaEstadoCompletedEventHandler(ByVal sender As Object, ByVal e As OnlineConsultaEstadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class OnlineConsultaEstadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub OnlineGenerationCompletedEventHandler(ByVal sender As Object, ByVal e As OnlineGenerationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class OnlineGenerationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ConsultCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
